
all: answer1 answer2 answer3 answer4 answer5_1 answer5_2 answer6 answer7

clean:
	rm -f answer1 answer2 answer3 answer4 answer5_1 answer5_2 answer6 answer7

answer1: answer1.c
	gcc -o answer1 answer1.c -Wall

answer2: answer2.c
	gcc -o answer2 answer2.c -Wall

answer3: answer3.c
	gcc -o answer3 answer3.c -Wall

answer4: answer4.c
	gcc -o answer4 answer4.c -Wall
	
answer5_1: answer5_1.c
	gcc -o answer5_1 answer5_1.c -Wall
	
answer5_2: answer5_2.c
	gcc -o answer5_2 answer5_2.c -Wall
	
answer6: answer6.c
	gcc -o answer6 answer6.c -Wall
	
answer7: answer7.c
	gcc -o answer7 answer7.c -Wall
